/**
 *  This controller will handle only those events generated by the MyApp.view.employee.List
 */
Ext.define('MyApp.controller.employee.List', {
    extend: 'Ext.app.Controller',

    config: {

        refs: {
            list: 'employeelist'
        },

        control: {

            'employeelist': {
                'itemtap': 'showEmployeeForm'
            }

        }
    },

    /**
     * init method is called when the application launch. So here we setup the listeners on the application bus.
     */
    init: function(){
        this.getApplication().on({
            'showemployeelist': this.showEmployeeList,
            scope: this
        });
    },


    /**
     * A listener for showemployeelist application event. This method will display the list by setting it as the 
     * active item in its parent container, which we know has a card layout.
     */
    showEmployeeList: function(){
        var me = this,
            list = me.getList(),
            container = list.up('container');

        container.setActiveItem(list);
    },

    /**
     * When a user taps on an employee item in the list we just fire an event on the application bus
     * to let some other controller take care of it by doing something with that particular record.
     */
    showEmployeeForm: function(list, index, target, record, e, eOpts){
        this.getApplication().fireEvent('showemployeeform', record);
    }
});
